# Generated by Django 3.2.4 on 2021-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('street', models.CharField(max_length=20, verbose_name='Улица')),
                ('house', models.IntegerField(verbose_name='Дом')),
                ('flat', models.IntegerField(blank=True, verbose_name='Квартира')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15, verbose_name='Производитель')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('socket', models.CharField(max_length=15, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=15, verbose_name='Чипсет')),
                ('memory_slots', models.IntegerField(verbose_name='Количетсов слотов памяти')),
                ('max_memory_frequency', models.IntegerField(verbose_name='Максимальная частота памяти')),
                ('quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='images/mother/', verbose_name='Изображение материнской платы')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('id_client', models.IntegerField(verbose_name='Идентификатор клиента')),
                ('id_proc', models.IntegerField(blank=True, verbose_name='Идентификатор процессора')),
                ('id_video', models.IntegerField(blank=True, verbose_name='Идентификатор видеокарты')),
                ('id_mother', models.IntegerField(blank=True, verbose_name='Идентификатор материнской платы')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15, verbose_name='Производитель')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('frequency', models.IntegerField(verbose_name='Частота')),
                ('socket', models.CharField(max_length=15, verbose_name='Сокет')),
                ('cores', models.IntegerField(verbose_name='Количество ядер')),
                ('threads', models.IntegerField(verbose_name='Количество потоков')),
                ('quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='images/proc/', verbose_name='Изображение процессора')),
            ],
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15, verbose_name='Производитель')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('memory_type', models.CharField(max_length=6, verbose_name='Тип памяти')),
                ('memory_size', models.IntegerField(verbose_name='Количество памяти')),
                ('quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='images/video/', verbose_name='Изображение видеокарты')),
            ],
        ),
    ]
