# Generated by Django 3.2.4 on 2021-06-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=20)),
                ('house', models.IntegerField()),
                ('flat', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mother', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=25)),
                ('socket', models.CharField(max_length=15)),
                ('chipset', models.CharField(max_length=15)),
                ('memory_slots', models.IntegerField()),
                ('max_memory_frequency', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/mother/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.IntegerField()),
                ('id_proc', models.IntegerField(blank=True)),
                ('id_video', models.IntegerField(blank=True)),
                ('id_mother', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proc', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=25)),
                ('frequency', models.IntegerField()),
                ('socket', models.CharField(max_length=15)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/proc/')),
            ],
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=25)),
                ('memory_type', models.CharField(max_length=6)),
                ('memory_size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/video/')),
            ],
        ),
    ]
