# Generated by Django 3.2.4 on 2021-06-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='flat',
            field=models.CharField(blank=True, max_length=5, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='client',
            name='house',
            field=models.CharField(max_length=5, verbose_name='Дом'),
        ),
    ]
