# Generated by Django 3.2.4 on 2021-07-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.motherboard', verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_proc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.processor', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.videocard', verbose_name='Видеокарта'),
        ),
    ]
